apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-invoices-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asp-invoices-client
  template:
    metadata:
      labels:
        app: asp-invoices-client
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: 'kubernetes.io/hostname'
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: asp-invoices-client
      containers:
        - name: client
          image: alexandermatveev2908/asp-invoices-client:latest
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: pfn-job-application-tracker
